package com.student.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.student.entity.Studnet;

import com.student.dao.StudnetDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studnetDaoConfig;

    private final StudnetDao studnetDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studnetDaoConfig = daoConfigMap.get(StudnetDao.class).clone();
        studnetDaoConfig.initIdentityScope(type);

        studnetDao = new StudnetDao(studnetDaoConfig, this);

        registerDao(Studnet.class, studnetDao);
    }
    
    public void clear() {
        studnetDaoConfig.getIdentityScope().clear();
    }

    public StudnetDao getStudnetDao() {
        return studnetDao;
    }

}
